apiVersion: apps/v1
kind: Deployment
metadata:
  name: break-reminder-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: break-reminder
  template:
    metadata:
      labels:
        app: break-reminder
    spec:
      containers:
        - name: break-reminder
          image: Snigdha1222/break-reminder:latest
          ports:
            - containerPort: 5000
          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 5
